[package]
name = "cli"
version = "0.18.0"
edition = "2021"
authors = ["bartosz.ciesla@gmail.com"]
repository = "https://github.com/iggy-rs/iggy"
homepage = "https://iggy.rs"

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
clap = { version = "4.5.0", features = ["derive"] }
clap_complete = "4.4.10"
figlet-rs = "0.1.5"
iggy = { path = "../sdk", features = ["iggy-cli"] }
keyring = "2.3.2"
passterm = "2.0.1"
thiserror = "1.0.56"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17" }

[[bin]]
name = "iggy"
path = "src/main.rs"
