[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
bytes = "1.6.0"
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.0.4"
derive_more = "0.99.17"
figlet-rs = "0.1.5"
futures = "0.3.30"
human_format = "1.1.0"
iggy = { path = "../sdk" }
integration = { path = "../integration" }
nonzero_lit = "0.1.2"
quinn = { version = "0.11.0" }
rustls = { version = "0.21.11" }
serde = { version = "1.0.202", features = ["derive"] }
thiserror = "1.0.60"
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.13"
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.16" }

[[bin]]
name = "iggy-bench"
path = "src/main.rs"
