[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
bytes = "1.4.0"
clap = { version = "4.4.18", features = ["derive"] }
colored = "2.0.4"
derive_more = "0.99.17"
figlet-rs = "0.1.5"
futures = "0.3.30"
human_bytes = "0.4.3"
human_format = "1.0.3"
iggy = { path = "../sdk" }
integration = { path = "../integration" }
nonzero_lit = "0.1.2"
quinn = { version = "0.10.2" }
rustls = { version = "0.21.10" }
serde = { version = "1.0.196", features = ["derive"] }
thiserror = "1.0.56"
tokio = { version = "1.36.0", features = ["full"] }
toml = "0.8.9"
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.16" }
criterion = "0.5.1"

[[bin]]
name = "iggy-bench"
path = "src/main.rs"

[[bench]]
name = "tcp"
harness = false
