[package]
name = "integration"
version = "0.0.1"
edition = "2021"

[dependencies]
assert_cmd = "2.0.13"
async-trait = "0.1.77"
byte-unit = { version = "5.1.4", default-features = false, features = [
    "serde",
    "byte",
] }
bytes = "1.4.0"
derive_more = "0.99.17"
futures = "0.3.30"
humantime = "2.1.0"
iggy = { path = "../sdk", features = ["iggy-cli"] }
keyring = "2.3.1"
libc = "0.2.147"
predicates = "3.1.0"
regex = "1.10.3"
rand = "0.8.5"
serial_test = "3.0.0"
server = { path = "../server" }
sled = "0.34.7"
tokio = { version = "1.28.2", features = ["full"] }
toml = "0.8.8"
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "zerocopy"] }
xxhash-rust = { version = "0.8.8", features = ["xxh32"] }

# Some tests are failing in CI due to lack of IPv6 interfaces
# inside the docker container. This is a temporary workaround (hopefully).
[features]
ci-qemu = []
